name: Thea
favicon: null
layout_spectrum: 0.23682
typography_spectrum: 0.29551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#421c51'
    - '#bc5e94'
    - '#7a3779'
    - '#ee97a0'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
