name: Thea
favicon: null
layout_spectrum: 0.8767391438595951
typography_spectrum: 0.6010082829743624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#003152'
    - '#a2d3f6'
    - '#438ebf'
    - '#ede8e5'
  brandStrength: 0.233784917043522
  lightness: 0.2170741178561002
  saturation: 0.8640637730713934
  rhythmicContrast: 0.05156392534263432
purpose: []
